presidentdata=[{'Dates': 'April 30, 1789-March 4, 1797',
  'Height': 320,
  'President': 'George Washington',
  'Title': '1st president of the United States from 1789 to 1797',
  'Width': 264,
  'WikiURL': '/wiki/George_Washington',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/264px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg',
  'text': None},
 {'Dates': 'March 4, 1797-March 4, 1801',
  'Height': 320,
  'President': 'John Adams',
  'Title': '2nd president of the United States (1797-1801)',
  'Width': 264,
  'WikiURL': '/wiki/John_Adams',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Gilbert_Stuart%2C_John_Adams%2C_c._1800-1815%2C_NGA_42933.jpg/264px-Gilbert_Stuart%2C_John_Adams%2C_c._1800-1815%2C_NGA_42933.jpg',
  'text': None},
 {'Dates': 'March 4, 1801-March 4, 1809',
  'Height': 320,
  'President': 'Thomas Jefferson',
  'Title': '3rd president of the United States (1801-09)',
  'Width': 260,
  'WikiURL': '/wiki/Thomas_Jefferson',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Official_Presidential_portrait_of_Thomas_Jefferson_%28by_Rembrandt_Peale%2C_1800%29%28cropped%29.jpg/260px-Official_Presidential_portrait_of_Thomas_Jefferson_%28by_Rembrandt_Peale%2C_1800%29%28cropped%29.jpg',
  'text': None},
 {'Dates': 'March 4, 1809-March 4, 1817',
  'Height': 320,
  'President': 'James Madison',
  'Title': '4th president of the United States',
  'Width': 262,
  'WikiURL': '/wiki/James_Madison',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/James_Madison%28cropped%29%28c%29.jpg/262px-James_Madison%28cropped%29%28c%29.jpg',
  'text': None},
 {'Dates': 'March 4, 1817-March 4, 1825',
  'Height': 320,
  'President': 'James Monroe',
  'Title': '5th president of the United States (1817-25)',
  'Width': 266,
  'WikiURL': '/wiki/James_Monroe',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/James_Monroe_White_House_portrait_1819.jpg/266px-James_Monroe_White_House_portrait_1819.jpg',
  'text': None},
 {'Dates': 'March 4, 1825-March 4, 1829',
  'Height': 320,
  'President': 'John Quincy Adams',
  'Title': '6th president of the United States',
  'Width': 244,
  'WikiURL': '/wiki/John_Quincy_Adams',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/John_Q._Adams.jpg/244px-John_Q._Adams.jpg',
  'text': None},
 {'Dates': 'March 4, 1829-March 4, 1837',
  'Height': 320,
  'President': 'Andrew Jackson',
  'Title': '7th president of the United States (1829-37)',
  'Width': 264,
  'WikiURL': '/wiki/Andrew_Jackson',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Andrew_jackson_head.jpg/264px-Andrew_jackson_head.jpg',
  'text': None},
 {'Dates': 'March 4, 1837-March 4, 1841',
  'Height': 320,
  'President': 'Martin Van Buren',
  'Title': '8th president of the United States (1837-41)',
  'Width': 255,
  'WikiURL': '/wiki/Martin_Van_Buren',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Martin_Van_Buren_by_Mathew_Brady_c1855-58.jpg/255px-Martin_Van_Buren_by_Mathew_Brady_c1855-58.jpg',
  'text': None},
 {'Dates': 'March 4, 1841-April 4, 1841',
  'Height': 320,
  'President': 'William Henry Harrison',
  'Title': '9th president of the United States (March-April 1841)',
  'Width': 265,
  'WikiURL': '/wiki/William_Henry_Harrison',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/William_Henry_Harrison_by_James_Reid_Lambdin%2C_1835_crop.jpg/265px-William_Henry_Harrison_by_James_Reid_Lambdin%2C_1835_crop.jpg',
  'text': None},
 {'Dates': 'April 4, 1841[i]-March 4, 1845',
  'Height': 320,
  'President': 'John Tyler',
  'Title': '10th president of the United States (1841-45)',
  'Width': 240,
  'WikiURL': '/wiki/John_Tyler',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/John_Tyler_%28cropped_3x4%29.png/240px-John_Tyler_%28cropped_3x4%29.png',
  'text': None},
 {'Dates': 'March 4, 1845-March 4, 1849',
  'Height': 320,
  'President': 'James K. Polk',
  'Title': '11th president of the United States (1845-49)',
  'Width': 255,
  'WikiURL': '/wiki/James_K._Polk',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Polk_crop.jpg/255px-Polk_crop.jpg',
  'text': None},
 {'Dates': 'March 4, 1849-July 9, 1850',
  'Height': 320,
  'President': 'Zachary Taylor',
  'Title': '12th president of the United States (1849-50)',
  'Width': 243,
  'WikiURL': '/wiki/Zachary_Taylor',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Zachary_Taylor_restored_and_cropped.jpg/243px-Zachary_Taylor_restored_and_cropped.jpg',
  'text': None},
 {'Dates': 'July 9, 1850[k]-March 4, 1853',
  'Height': 320,
  'President': 'Millard Fillmore',
  'Title': '13th president of the United States (1850-53)',
  'Width': 252,
  'WikiURL': '/wiki/Millard_Fillmore',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Fillmore.jpg/252px-Fillmore.jpg',
  'text': None},
 {'Dates': 'March 4, 1853-March 4, 1857',
  'Height': 320,
  'President': 'Franklin Pierce',
  'Title': '14th president of the United States (1853-57)',
  'Width': 257,
  'WikiURL': '/wiki/Franklin_Pierce',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Mathew_Brady_-_Franklin_Pierce_-_alternate_crop.jpg/257px-Mathew_Brady_-_Franklin_Pierce_-_alternate_crop.jpg',
  'text': None},
 {'Dates': 'March 4, 1857-March 4, 1861',
  'Height': 320,
  'President': 'James Buchanan',
  'Title': '15th president of the United States (1857-61)',
  'Width': 277,
  'WikiURL': '/wiki/James_Buchanan',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/James_Buchanan.jpg/277px-James_Buchanan.jpg',
  'text': None},
 {'Dates': 'March 4, 1861-April 15, 1865',
  'Height': 320,
  'President': 'Abraham Lincoln',
  'Title': '16th president of the United States (1861-65)',
  'Width': 248,
  'WikiURL': '/wiki/Abraham_Lincoln',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg/248px-Abraham_Lincoln_O-77_matte_collodion_print.jpg',
  'text': None},
 {'Dates': 'April 15, 1865-March 4, 1869',
  'Height': 320,
  'President': 'Andrew Johnson',
  'Title': '17th president of the United States (1865-69)',
  'Width': 249,
  'WikiURL': '/wiki/Andrew_Johnson',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Andrew_Johnson_photo_portrait_head_and_shoulders%2C_c1870-1880-Edit1.jpg/249px-Andrew_Johnson_photo_portrait_head_and_shoulders%2C_c1870-1880-Edit1.jpg',
  'text': None},
 {'Dates': 'March 4, 1869-March 4, 1877',
  'Height': 320,
  'President': 'Ulysses S. Grant',
  'Title': 'Commanding general of the United States Army (1864-69) and 18th '
           'president of the United States (1869-77)',
  'Width': 240,
  'WikiURL': '/wiki/Ulysses_S._Grant',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Ulysses_S._Grant_1870-1880.jpg/240px-Ulysses_S._Grant_1870-1880.jpg',
  'text': None},
 {'Dates': 'March 4, 1877-March 4, 1881',
  'Height': 320,
  'President': 'Rutherford B. Hayes',
  'Title': '19th president of the United States (1877-81)',
  'Width': 263,
  'WikiURL': '/wiki/Rutherford_B._Hayes',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/President_Rutherford_Hayes_1870_-_1880_Restored.jpg/263px-President_Rutherford_Hayes_1870_-_1880_Restored.jpg',
  'text': None},
 {'Dates': 'March 4, 1881-September 19, 1881',
  'Height': 320,
  'President': 'James A. Garfield',
  'Title': '20th president of the United States',
  'Width': 252,
  'WikiURL': '/wiki/James_A._Garfield',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/James_Abram_Garfield%2C_photo_portrait_seated.jpg/252px-James_Abram_Garfield%2C_photo_portrait_seated.jpg',
  'text': None},
 {'Dates': 'September 19, 1881[p]-March 4, 1885',
  'Height': 320,
  'President': 'Chester A. Arthur',
  'Title': '21st president of the United States (1881-85)',
  'Width': 259,
  'WikiURL': '/wiki/Chester_A._Arthur',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Chester_Alan_Arthur_%28cropped%29.jpg/259px-Chester_Alan_Arthur_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'March 4, 1889-March 4, 1893',
  'Height': 320,
  'President': 'Benjamin Harrison',
  'Title': '23rd president of the United States (1833-1901)',
  'Width': 252,
  'WikiURL': '/wiki/Benjamin_Harrison',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg/252px-Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg',
  'text': None},
 {'Dates': 'March 4, 1893-March 4, 1897',
  'Height': 320,
  'President': 'Grover Cleveland',
  'Title': '22nd and 24th president of the United States (1885-89 and 1893-97)',
  'Width': 252,
  'WikiURL': '/wiki/Grover_Cleveland',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Grover_Cleveland_-_NARA_-_518139.jpg/252px-Grover_Cleveland_-_NARA_-_518139.jpg',
  'text': None},
 {'Dates': 'March 4, 1897-September 14, 1901',
  'Height': 320,
  'President': 'William McKinley',
  'Title': '25th president of the United States (1897-1901)',
  'Width': 251,
  'WikiURL': '/wiki/William_McKinley',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/McKinley_%28cropped%29.jpg/251px-McKinley_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'September 14, 1901-March 4, 1909',
  'Height': 320,
  'President': 'Theodore Roosevelt',
  'Title': '26th president of the United States',
  'Width': 238,
  'WikiURL': '/wiki/Theodore_Roosevelt',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/President_Roosevelt_-_Pach_Bros_%28cropped%29.jpg/238px-President_Roosevelt_-_Pach_Bros_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'March 4, 1909-March 4, 1913',
  'Height': 320,
  'President': 'William Howard Taft',
  'Title': '27th president (1909-13) and 10th chief justice of the United '
           'States',
  'Width': 244,
  'WikiURL': '/wiki/William_Howard_Taft',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/William_Howard_Taft_-_Harris_and_Ewing.jpg/244px-William_Howard_Taft_-_Harris_and_Ewing.jpg',
  'text': None},
 {'Dates': 'March 4, 1913-March 4, 1921',
  'Height': 320,
  'President': 'Woodrow Wilson',
  'Title': '28th president of the United States (1913-21)',
  'Width': 234,
  'WikiURL': '/wiki/Woodrow_Wilson',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Thomas_Woodrow_Wilson%2C_Harris_%26_Ewing_bw_photo_portrait%2C_1919_%28cropped%29.jpg/234px-Thomas_Woodrow_Wilson%2C_Harris_%26_Ewing_bw_photo_portrait%2C_1919_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'March 4, 1921-August 2, 1923',
  'Height': 320,
  'President': 'Warren G. Harding',
  'Title': '29th president of the United States (1921-23)',
  'Width': 235,
  'WikiURL': '/wiki/Warren_G._Harding',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Warren_G_Harding-Harris_%26_Ewing.jpg/235px-Warren_G_Harding-Harris_%26_Ewing.jpg',
  'text': None},
 {'Dates': 'August 2, 1923[r]-March 4, 1929',
  'Height': 320,
  'President': 'Calvin Coolidge',
  'Title': '30th president of the United States (1923-29)',
  'Width': 240,
  'WikiURL': '/wiki/Calvin_Coolidge',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Calvin_Coolidge_cph.3g10777_%28cropped%29.jpg/240px-Calvin_Coolidge_cph.3g10777_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'March 4, 1929-March 4, 1933',
  'Height': 320,
  'President': 'Herbert Hoover',
  'Title': '31st president of the United States (1874-1964)',
  'Width': 240,
  'WikiURL': '/wiki/Herbert_Hoover',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/President_Hoover_portrait.jpg/240px-President_Hoover_portrait.jpg',
  'text': None},
 {'Dates': 'March 4, 1933-April 12, 1945',
  'Height': 320,
  'President': 'Franklin D. Roosevelt',
  'Title': '32nd president of the United States',
  'Width': 222,
  'WikiURL': '/wiki/Franklin_D._Roosevelt',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/FDR_1944_Color_Portrait.jpg/222px-FDR_1944_Color_Portrait.jpg',
  'text': None},
 {'Dates': 'April 12, 1945-January 20, 1953',
  'Height': 320,
  'President': 'Harry S. Truman',
  'Title': '33rd president of the United States (1945-53)',
  'Width': 237,
  'WikiURL': '/wiki/Harry_S._Truman',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/TRUMAN_58-766-06_%28cropped%29.jpg/237px-TRUMAN_58-766-06_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'January 20, 1953-January 20, 1961',
  'Height': 320,
  'President': 'Dwight D. Eisenhower',
  'Title': 'American army general and 34th president of the United States '
           '(1953-61)',
  'Width': 255,
  'WikiURL': '/wiki/Dwight_D._Eisenhower',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Dwight_D._Eisenhower%2C_official_photo_portrait%2C_May_29%2C_1959.jpg/255px-Dwight_D._Eisenhower%2C_official_photo_portrait%2C_May_29%2C_1959.jpg',
  'text': None},
 {'Dates': 'January 20, 1961-November 22, 1963',
  'Height': 320,
  'President': 'John F. Kennedy',
  'Title': '35th president of the United States',
  'Width': 247,
  'WikiURL': '/wiki/John_F._Kennedy',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg/247px-John_F._Kennedy%2C_White_House_color_photo_portrait.jpg',
  'text': None},
 {'Dates': 'November 22, 1963-January 20, 1969',
  'Height': 320,
  'President': 'Lyndon B. Johnson',
  'Title': '36th president of the United States',
  'Width': 241,
  'WikiURL': '/wiki/Lyndon_B._Johnson',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/37_Lyndon_Johnson_3x4.jpg/241px-37_Lyndon_Johnson_3x4.jpg',
  'text': None},
 {'Dates': 'January 20, 1969-August 9, 1974',
  'Height': 320,
  'President': 'Richard Nixon',
  'Title': '37th president of the United States (1969-74)',
  'Width': 240,
  'WikiURL': '/wiki/Richard_Nixon',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Richard_Nixon_presidential_portrait_%281%29.jpg/240px-Richard_Nixon_presidential_portrait_%281%29.jpg',
  'text': None},
 {'Dates': 'August 9, 1974-January 20, 1977',
  'Height': 320,
  'President': 'Gerald Ford',
  'Title': '38th president of the United States (1974-77)',
  'Width': 257,
  'WikiURL': '/wiki/Gerald_Ford',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Gerald_Ford_presidential_portrait_%28cropped%29.jpg/257px-Gerald_Ford_presidential_portrait_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'January 20, 1977-January 20, 1981',
  'Height': 320,
  'President': 'Jimmy Carter',
  'Title': '39th president of the United States',
  'Width': 240,
  'WikiURL': '/wiki/Jimmy_Carter',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/JimmyCarterPortrait_%28cropped%29.jpg/240px-JimmyCarterPortrait_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'January 20, 1981-January 20, 1989',
  'Height': 320,
  'President': 'Ronald Reagan',
  'Title': '40th president of the United States (1981-89)',
  'Width': 256,
  'WikiURL': '/wiki/Ronald_Reagan',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Official_Portrait_of_President_Reagan_1981.jpg/256px-Official_Portrait_of_President_Reagan_1981.jpg',
  'text': None},
 {'Dates': 'January 20, 1989-January 20, 1993',
  'Height': 320,
  'President': 'George H. W. Bush',
  'Title': '41st president of the United States',
  'Width': 244,
  'WikiURL': '/wiki/George_H._W._Bush',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/George_H._W._Bush_presidential_portrait_%28cropped%29.jpg/244px-George_H._W._Bush_presidential_portrait_%28cropped%29.jpg',
  'text': None},
 {'Dates': 'January 20, 1993-January 20, 2001',
  'Height': 320,
  'President': 'Bill Clinton',
  'Title': '42nd president of the United States',
  'Width': 245,
  'WikiURL': '/wiki/Bill_Clinton',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bill_Clinton.jpg/245px-Bill_Clinton.jpg',
  'text': None},
 {'Dates': 'January 20, 2001-January 20, 2009',
  'Height': 320,
  'President': 'George W. Bush',
  'Title': '43rd president of the United States',
  'Width': 242,
  'WikiURL': '/wiki/George_W._Bush',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/George-W-Bush.jpeg/242px-George-W-Bush.jpeg',
  'text': None},
 {'Dates': 'January 20, 2009-January 20, 2017',
  'Height': 320,
  'President': 'Barack Obama',
  'Title': '44th president of the United States',
  'Width': 256,
  'WikiURL': '/wiki/Barack_Obama',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/256px-President_Barack_Obama.jpg',
  'text': None},
 {'Dates': 'January 20, 2017-January 20, 2021',
  'Height': 320,
  'President': 'Donald Trump',
  'Title': '45th president of the United States',
  'Width': 253,
  'WikiURL': '/wiki/Donald_Trump',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Donald_Trump_official_portrait.jpg/253px-Donald_Trump_official_portrait.jpg',
  'text': None},
 {'Dates': 'January 20, 2021-Incumbent',
  'Height': 320,
  'President': 'Joe Biden',
  'Title': '46th president of the United States',
  'Width': 256,
  'WikiURL': '/wiki/Joe_Biden',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Joe_Biden_presidential_portrait.jpg/256px-Joe_Biden_presidential_portrait.jpg',
  'text': None},
]