#global monarchdata
from browser import window
global mmm
window.mmm=123
window.monarchdata=[{'Dates': '924 - 939',
  'Height': 320,
  'Monarch': 'Aethelstan',
  'Title': 'Aethelstan',
  'Width': 229,
  'WikiURL': '/wiki/%C3%86thelstan',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Athelstan_%28cropped%29.jpg/229px-Athelstan_%28cropped%29.jpg',
  'text': '10th-century King of the Anglo-Saxons, King of the English'},
 {'Dates': '978-1013',
  'Height': 320,
  'Monarch': 'Aethelred the Unready',
  'Title': 'Aethelred the Unready',
  'Width': 189,
  'WikiURL': '/wiki/%C3%86thelred_the_Unready',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Ethelred_the_Unready.jpg/189px-Ethelred_the_Unready.jpg',
  'text': '10th and 11th-century King of England'},
 {'Dates': '1016-35',
  'Height': 320,
  'Monarch': 'Cnut the Great',
  'Title': 'Cnut The Great',
  'Width': 229,
  'WikiURL': '/wiki/Cnut_the_Great',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Canute_and_%C3%86lfgifu_cropped_%28Canute%29.jpg/229px-Canute_and_%C3%86lfgifu_cropped_%28Canute%29.jpg',
  'text': '10th and 11th-century King of Denmark, Norway, and England'},
 {'Dates': '1024-1066',
  'Height': 320,
  'Monarch': 'Edward the Confessor',
  'Title': 'Edward the Confessor',
  'Width': 292,
  'WikiURL': '/wiki/Edward_the_Confessor',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Bayeux_Tapestry_scene1_EDWARD_REX.jpg/292px-Bayeux_Tapestry_scene1_EDWARD_REX.jpg',
  'text': '11th-century Anglo-Saxon King of England'},
 {'Dates': '1066-1087',
  'Height': 320,
  'Monarch': 'William the Conqueror',
  'Title': 'William I',
  'Width': 292,
  'WikiURL': '/wiki/William_the_Conqueror',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Bayeuxtapestrywilliamliftshishelm.jpg/150px-Bayeuxtapestrywilliamliftshishelm.jpg',
  'text': 'King of England, Duke of Normandy'},
 {'Dates': '1087-1100',
  'Height': 320,
  'Monarch': 'William II of England',
  'Title': 'William II',
  'Width': 192,
  'WikiURL': '/wiki/William_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/William_II_of_England.jpg/192px-William_II_of_England.jpg',
  'text': 'King of England'},
 {'Dates': '1100-1135',
  'Height': 320,
  'Monarch': 'Henry I of England',
  'Title': 'Henry I',
  'Width': 196,
  'WikiURL': '/wiki/Henry_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Henry1.jpg/196px-Henry1.jpg',
  'text': 'King of England from 1100 to 1135'},
 {'Dates': '1135-1154',
  'Height': 320,
  'Monarch': 'Stephen of England',
  'Title': 'King Stephen',
  'Width': 203,
  'WikiURL': '/wiki/Stephen_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Stepan_Blois.jpg/203px-Stepan_Blois.jpg',
  'text': '12th-century King of England and Count of Boulogne'},
 {'Dates': '1154-1189',
  'Height': 180,
  'Monarch': 'Henry II of England',
  'Title': 'Henry II',
  'Width': 320,
  'WikiURL': '/wiki/Henry_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Church_of_Fontevraud_Abbey_Henry_II_effigy.jpg/320px-Church_of_Fontevraud_Abbey_Henry_II_effigy.jpg',
  'text': '12th-century King of England, Duke of Aquitaine, and ruler of other '
          'European lands'},
 {'Dates': '1189-1199',
  'Height': 180,
  'Monarch': 'Richard I of England',
  'Title': 'Richard I',
  'Width': 320,
  'WikiURL': '/wiki/Richard_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Church_of_Fontevraud_Abbey_Richard_I_effigy.jpg/320px-Church_of_Fontevraud_Abbey_Richard_I_effigy.jpg',
  'text': '12th-century King of England and crusader'},
 {'Dates': '1199-1216',
  'Height': 320,
  'Monarch': 'John of England',
  'Title': 'King John',
  'Width': 136,
  'WikiURL': '/wiki/John_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Jan_tomb.jpg/136px-Jan_tomb.jpg',
  'text': '13th-century King of England and grantor of Magna Carta'},
 {'Dates': '1216-1272',
  'Height': 254,
  'Monarch': 'Henry III of England',
  'Title': 'Henry III',
  'Width': 320,
  'WikiURL': '/wiki/Henry_III_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Henry_III_funeral_head.jpg/320px-Henry_III_funeral_head.jpg',
  'text': '13th-century King of England and Duke of Aquitaine'},
 {'Dates': '1272-1307',
  'Height': 320,
  'Monarch': 'Edward I of England',
  'Title': 'Edward I',
  'Width': 240,
  'WikiURL': '/wiki/Edward_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Edward_I_-_Westminster_Abbey_Sedilia.jpg/240px-Edward_I_-_Westminster_Abbey_Sedilia.jpg',
  'text': 'King of England from 1272 to 1307'},
 {'Dates': '1307-1327',
  'Height': 213,
  'Monarch': 'Edward II of England',
  'Title': 'Edward II',
  'Width': 320,
  'WikiURL': '/wiki/Edward_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Edward_II_-_detail_of_tomb.jpg/320px-Edward_II_-_detail_of_tomb.jpg',
  'text': '14th-century King of England and Duke of Aquitaine'},
 {'Dates': '1327-1377',
  'Height': 320,
  'Monarch': 'Edward III of England',
  'Title': 'Edward III',
  'Width': 314,
  'WikiURL': '/wiki/Edward_III_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Edward-III-king-England.jpg/314px-Edward-III-king-England.jpg',
  'text': '14th-century King of England and Duke of Aquitaine'},
 {'Dates': '1377-1399',
  'Height': 320,
  'Monarch': 'Richard II of England',
  'Title': 'Richard II',
  'Width': 235,
  'WikiURL': '/wiki/Richard_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Richard_II_King_of_England.jpg/235px-Richard_II_King_of_England.jpg',
  'text': '14th-century King of England and Duke of Aquitaine'},
 {'Dates': '1399-1413',
  'Height': 320,
  'Monarch': 'Henry IV of England',
  'Title': 'Henry IV',
  'Width': 268,
  'WikiURL': '/wiki/Henry_IV_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Illumination_of_Henry_IV_%28cropped%29.jpg/268px-Illumination_of_Henry_IV_%28cropped%29.jpg',
  'text': '15th-century King of England'},
 {'Dates': '1413-1422',
  'Height': 320,
  'Monarch': 'Henry V of England',
  'Title': 'Henry V',
  'Width': 253,
  'WikiURL': '/wiki/Henry_V_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Henry_V_of_England_miniature.jpg/253px-Henry_V_of_England_miniature.jpg',
  'text': '15th-century King of England and Duke of Aquitaine'},
 {'Dates': '1422-1461',
  'Height': 320,
  'Monarch': 'Henry VI of England',
  'Title': 'Henry VI',
  'Width': 250,
  'WikiURL': '/wiki/Henry_VI_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/King_Henry_VI_from_NPG_%282%29.jpg/250px-King_Henry_VI_from_NPG_%282%29.jpg',
  'text': '15th-century King of England'},
 {'Dates': '1461-1470',
  'Height': 320,
  'Monarch': 'Edward IV of England',
  'Title': 'Edward IV',
  'Width': 249,
  'WikiURL': '/wiki/Edward_IV_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/King_Edward_IV.jpg/249px-King_Edward_IV.jpg',
  'text': 'King of England from 1461 to 1470 and 1471 to 1483'},
 {'Dates': '1483-1483',
  'Height': 320,
  'Monarch': 'Edward V of England',
  'Title': 'Edward V',
  'Width': 249,
  'WikiURL': '/wiki/Edward_V_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/King_Edward_V_from_NPG.jpg/249px-King_Edward_V_from_NPG.jpg',
  'text': '15th-century King of England and one of the Princes in the Tower'},
 {'Dates': '1483-1485',
  'Height': 320,
  'Monarch': 'Richard III of England',
  'Title': 'Richard III',
  'Width': 237,
  'WikiURL': '/wiki/Richard_III_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Richard_III_earliest_surviving_portrait.jpg/237px-Richard_III_earliest_surviving_portrait.jpg',
  'text': '15th-century King of England'},
 {'Dates': '1485-1509',
  'Height': 320,
  'Monarch': 'Henry VII of England',
  'Title': 'Henry VII',
  'Width': 232,
  'WikiURL': '/wiki/Henry_VII_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Enrique_VII_de_Inglaterra%2C_por_un_artista_an%C3%B3nimo.jpg/232px-Enrique_VII_de_Inglaterra%2C_por_un_artista_an%C3%B3nimo.jpg',
  'text': 'King of England, 1485-1509'},
 {'Dates': '1509-1547',
  'Height': 320,
  'Monarch': 'Henry VIII of England',
  'Title': 'Henry VIII',
  'Width': 182,
  'WikiURL': '/wiki/Henry_VIII_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/After_Hans_Holbein_the_Younger_-_Portrait_of_Henry_VIII_-_Google_Art_Project.jpg/182px-After_Hans_Holbein_the_Younger_-_Portrait_of_Henry_VIII_-_Google_Art_Project.jpg',
  'text': '16th-century King of England'},
 {'Dates': '1547-1553',
  'Height': 320,
  'Monarch': 'Edward VI of England',
  'Title': 'Edward VI',
  'Width': 243,
  'WikiURL': '/wiki/Edward_VI_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Circle_of_William_Scrots_Edward_VI_of_England.jpg/243px-Circle_of_William_Scrots_Edward_VI_of_England.jpg',
  'text': '16th-century Tudor king of England'},
 {'Dates': '1553-1558',
  'Height': 320,
  'Monarch': 'Mary I of England',
  'Title': 'Mary I',
  'Width': 241,
  'WikiURL': '/wiki/Mary_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Anthonis_Mor_001.jpg/241px-Anthonis_Mor_001.jpg',
  'text': 'Queen of England and Ireland from 1553-1558'},
 {'Dates': '1558-1603',
  'Height': 320,
  'Monarch': 'Elizabeth I of England',
  'Title': 'Elizabeth I',
  'Width': 219,
  'WikiURL': '/wiki/Elizabeth_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Darnley_stage_3.jpg/219px-Darnley_stage_3.jpg',
  'text': 'Queen regnant of England and Ireland from 17 November 1558 until 24 '
          'March 1603'},
 {'Dates': '1603-1625',
  'Height': 320,
  'Monarch': 'James I of England',
  'Title': 'James I',
  'Width': 189,
  'WikiURL': '/wiki/James_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/JamesIEngland.jpg/189px-JamesIEngland.jpg',
  'text': '16th/17th-century King of Scotland, England and Ireland'},
 {'Dates': '1625-1649',
  'Height': 320,
  'Monarch': 'Charles I of England',
  'Title': 'Charles I',
  'Width': 185,
  'WikiURL': '/wiki/Charles_I_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/King_Charles_I_after_original_by_van_Dyck.jpg/185px-King_Charles_I_after_original_by_van_Dyck.jpg',
  'text': '17th-century monarch of England, Scotland and Ireland'},
 {'Dates': '1660-1685',
  'Height': 320,
  'Monarch': 'Charles II of England',
  'Title': 'Charles II',
  'Width': 251,
  'WikiURL': '/wiki/Charles_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/King_Charles_II_by_John_Michael_Wright_or_studio.jpg/251px-King_Charles_II_by_John_Michael_Wright_or_studio.jpg',
  'text': '17th-century monarch of England, Scotland and Ireland'},
 {'Dates': '1685-1688',
  'Height': 320,
  'Monarch': 'James II of England',
  'Title': 'James II',
  'Width': 256,
  'WikiURL': '/wiki/James_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/James_II_by_Peter_Lely.jpg/256px-James_II_by_Peter_Lely.jpg',
  'text': 'King of England, Scotland, and Ireland (1633-1701)'},
 {'Dates': '1689-1694',
  'Height': 320,
  'Monarch': 'Mary II of England',
  'Title': 'Mary II',
  'Width': 196,
  'WikiURL': '/wiki/Mary_II_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Mary_II_-_Kneller_1690.jpg/196px-Mary_II_-_Kneller_1690.jpg',
  'text': 'Joint Sovereign of England, Scotland, and Ireland (1662-1694)'},
 {'Dates': '1689-1702',
  'Height': 320,
  'Monarch': 'William III of England',
  'Title': 'William III',
  'Width': 260,
  'WikiURL': '/wiki/William_III_of_England',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/King_William_III_of_England%2C_%281650-1702%29.jpg/260px-King_William_III_of_England%2C_%281650-1702%29.jpg',
  'text': 'Prince of Orange; King of England, Scotland, and Ireland from '
          '1689-1702'},
 {'Dates': '1702-1714',
  'Height': 320,
  'Monarch': 'Anne, Queen of Great Britain',
  'Title': 'Queen Anne',
  'Width': 193,
  'WikiURL': '/wiki/Anne,_Queen_of_Great_Britain',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Dahl%2C_Michael_-_Queen_Anne_-_NPG_6187.jpg/193px-Dahl%2C_Michael_-_Queen_Anne_-_NPG_6187.jpg',
  'text': 'Queen of Britain and Ireland (r.1702-14)'},
 {'Dates': '1714-1727',
  'Height': 320,
  'Monarch': 'George I of Great Britain',
  'Title': 'George I',
  'Width': 225,
  'WikiURL': '/wiki/George_I_of_Great_Britain',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/King_George_I_by_Sir_Godfrey_Kneller%2C_Bt_%283%29.jpg/225px-King_George_I_by_Sir_Godfrey_Kneller%2C_Bt_%283%29.jpg',
  'text': 'King of Great Britain and Ireland (r. 1714-27), Elector of Hanover '
          '(r. 1698-1727)'},
 {'Dates': '1727-1760',
  'Height': 320,
  'Monarch': 'George II of the United Kingdom',
  'Title': 'George II',
  'Width': 194,
  'WikiURL': '/wiki/George_II_of_the_United_Kingdom',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/George_II_by_Thomas_Hudson.jpg/194px-George_II_by_Thomas_Hudson.jpg',
  'text': 'King of Great Britain and Ireland from 1727 to 1760'},
 {'Dates': '1760-1820',
  'Height': 320,
  'Monarch': 'George III of the United Kingdom',
  'Title': 'George III',
  'Width': 205,
  'WikiURL': '/wiki/George_III_of_the_United_Kingdom',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Allan_Ramsay_-_King_George_III_in_coronation_robes_-_Google_Art_Project.jpg/205px-Allan_Ramsay_-_King_George_III_in_coronation_robes_-_Google_Art_Project.jpg',
  'text': 'King of Great Britain and Ireland from 1760 to 1820'},
 {'Dates': '1820-1830',
  'Height': 320,
  'Monarch': 'George IV of the United Kingdom',
  'Title': 'George IV',
  'Width': 219,
  'WikiURL': '/wiki/George_IV_of_the_United_Kingdom',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/George_IV_1821_color.jpg/219px-George_IV_1821_color.jpg',
  'text': 'King of the United Kingdom and Hanover from 1820 to 1830'},
 {'Dates': '1830-1837',
  'Height': 320,
  'Monarch': 'William IV of the United Kingdom',
  'Title': 'William IV',
  'Width': 210,
  'WikiURL': '/wiki/William_IV_of_the_United_Kingdom',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/William_IV_crop.jpg/210px-William_IV_crop.jpg',
  'text': 'King of the United Kingdom of Great Britain and Ireland and of '
          'Hanover from 1830 to 1837'},
 {'Dates': '1837-1901',
  'Height': 320,
  'Monarch': 'Queen Victoria',
  'Title': 'Queen Victoria',
  'Width': 227,
  'WikiURL': '/wiki/Queen_Victoria',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Queen_Victoria_by_Bassano.jpg/227px-Queen_Victoria_by_Bassano.jpg',
  'text': 'Queen of the United Kingdom of Great Britain and Ireland '
          '(1837-1901) and Empress of India (1876-1901)'},
 {'Dates': '1901-1910',
  'Height': 320,
  'Monarch': 'Edward VII',
  'Title': 'Edward VII',
  'Width': 206,
  'WikiURL': '/wiki/Edward_VII',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/King-Edward-VII_%28cropped%29.jpg/206px-King-Edward-VII_%28cropped%29.jpg',
  'text': 'King of the United Kingdom from 1901 to 1910'},
 {'Dates': '1910-1936',
  'Height': 320,
  'Monarch': 'George V',
  'Title': 'George V',
  'Width': 227,
  'WikiURL': '/wiki/George_V',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/King_George_1923_LCCN2014715558_%28cropped%29.jpg/227px-King_George_1923_LCCN2014715558_%28cropped%29.jpg',
  'text': 'King of the United Kingdom and the British Dominions and Emperor of '
          'India (1910-1936)'},
 {'Dates': '1936-1936',
  'Height': 320,
  'Monarch': 'Edward VIII',
  'Title': 'Edward VIII',
  'Width': 237,
  'WikiURL': '/wiki/Edward_VIII',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/HRH_The_Prince_of_Wales_No_4_%28HS85-10-36416%29.jpg/237px-HRH_The_Prince_of_Wales_No_4_%28HS85-10-36416%29.jpg',
  'text': 'King of the United Kingdom and the British Dominions and Emperor of '
          'India, who abdicated in 1936'},
 {'Dates': '1936-1952',
  'Height': 320,
  'Monarch': 'George VI',
  'Title': 'George VI',
  'Width': 233,
  'WikiURL': '/wiki/George_VI',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/King_George_VI_LOC_matpc.14736_%28cleaned%29.jpg/233px-King_George_VI_LOC_matpc.14736_%28cleaned%29.jpg',
  'text': 'King of the United Kingdom and the British Dominions (1936-1952), '
          'last Emperor of India (1936-1947)'},
 {'Dates': '1952 -',
  'Height': 320,
  'Monarch': 'Elizabeth II',
  'Title': 'Elizabeth II',
  'Width': 242,
  'WikiURL': '/wiki/Elizabeth_II',
  'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Queen_Elizabeth_II_in_March_2015.jpg/242px-Queen_Elizabeth_II_in_March_2015.jpg',
  'text': 'Queen of the United Kingdom and 15 other Commonwealth realms'}]
